#!/usr/bin/with-contenv bash

# make our folders
mkdir -p \
	/config/projects

# install codiad and plugins
if [ ! -d "/config/www/.git" ]; then
	rm -rf /config/www/*
	git clone https://github.com/Codiad/Codiad /config/www
	[[ -e /config/www/config.php ]] && rm /config/www/config.php
fi

[[ ! -d "/config/www/plugins/Codiad-Collaborative-master/.git" ]] && \
	git clone https://github.com/Codiad/Codiad-Collaborative \
	/config/www/plugins/Codiad-Collaborative-master/

[[ ! -d "/config/www/plugins/Codiad-CodeGit-master/.git" ]] && \
	git clone https://github.com/Andr3as/Codiad-CodeGit \
	/config/www/plugins/Codiad-CodeGit-master/

[[ ! -d "/config/www/plugins/Codiad-DragDrop-master/.git" ]] && \
	git clone https://github.com/Andr3as/Codiad-DragDrop \
	/config/www/plugins/Codiad-DragDrop-master/

[[ ! -d "/config/www/plugins/Codiad-Terminal-master/.git" ]] && \
	git clone https://github.com/Fluidbyte/Codiad-Terminal \
	/config/www/plugins/Codiad-Terminal-master/

# configure projects folder
if [ ! -e /config/www/config.php ] ; then \
	INSTALL_SED=/config/www/components/install/process.php ;
	else INSTALL_SED=/config/www/config.php
fi

sed -i \
	's#define("WHITEPATHS", BASE_PATH . ",/home");#define("WHITEPATHS", BASE_PATH . ",/home,/config/projects");#g' \
	${INSTALL_SED}

# fix collaboration error
sed -i s/' echo formatJSEND("error","Warning: File ".'/'#echo formatJSEND("error","Warning: File ".'/ \
	/config/www/components/active/class.active.php

# permissions
chown -R abc:abc \
	/config
